collections:
  authors:
    output: true

theme: "just-the-docs"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: "dark"

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
